## Check health of the app
GET http://localhost:8085/health


### Get all todos
GET http://localhost:8085/api/todo

### POST one todo
POST http://localhost:8085/api/todo
Content-Type: application/json

{
    "description": "Sööda kassi2",
    "priority": 2,
    "isDone": false
}

### DELETE on endpoint
DELETE http://localhost:8085/api/todo/68d6ae9643f0db407eae0efb